[vcs]
type = "git"

[semver]
version = "0.0.1"
bump_commit_message_template = "bump: {prev_version_str} -> {version_str} [skip ci]"
version_tag_name_template = "v{version_str}"

[[semver.bump_rules]]
branch = "main"
when_breaking = "minor"
when_feat = "minor"
when_fix = "patch"

[[semver.version_files]]
path = "pyproject.toml"
prefix = "version"
section = "[tool.poetry]"
encoding = "utf-8"

[[semver.version_files]]
path = "modelity/__init__.py"

[[semver.changelog_files]]
path = "CHANGELOG.md"
encoding = "utf-8"
