version: 2.1

commands:
  configure-git:
    steps:
      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "circleci@noreply.circleci.com"

  install-deps:
    parameters:
      python_version:
        type: string
    steps:
      - restore_cache:
          name: restore dependency cache
          keys:
            - uv-py<<parameters.python_version>>-{{ checksum "uv.lock" }}
      - run: uv python pin <<parameters.python_version>>
      - run: uv sync
      - save_cache:
          name: save dependency cache
          key: uv-py<<parameters.python_version>>-{{ checksum "uv.lock" }}
          paths:
            - .venv

jobs:
  test:
    docker:
      - image: cimg/python:<<parameters.python_version>>
    parameters:
      python_version:
        type: string
    steps:
      - checkout
      - install-deps:
          python_version: <<parameters.python_version>>
      - run: uv run inv check

  bump:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - configure-git
      - add_ssh_keys
      - install-deps:
          python_version: "3.13"
      #- run: pip install bumpify
      - run: uvx --python=3.13 bumpify bump
      - run: git push --set-upstream origin $CIRCLE_BRANCH
      - run: git push --tags

  deploy:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - configure-git
      - install-deps:
          python_version: "3.13"
      - run: uv build
      - run: uv publish --dry-run --token $PYPI_API_TOKEN
      - run: uv publish --token $PYPI_API_TOKEN

workflows:
  test-bump-deploy:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      - bump:
          requires:
            - test
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
